name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    # - name: prepare system with prerequisites
       # run: sudo apt-get install -y hmmer ncbi-blast+ git libcurl4-openssl-dev build-essential curl
    - name: prep
      run: sudo apt-get install -y hmmer ncbi-blast+ git libcurl4-openssl-dev build-essential curl
    - name: make
      run: make
    - name: debug
      run: pwd -P && ls -al
    - name: download db
      run: cd /home/runner/work/amr/amr && ./amrfinder -u
    - name: make test
      run: make test
